@extends('admin.layout')
@section('title',$role->exists?'Modifier un role':'Creer un role')
@php($active='roles')
@section('content')
<div class="admin-page-heading"><div><p class="eyebrow">Permissions</p><h1>{{ $role->exists?'Modifier le role':'Nouveau role' }}</h1><p>Attribuez uniquement les acces necessaires au profil concerne.</p></div><a class="btn secondary" href="{{ route('admin.roles.index') }}">Retour aux roles</a></div>
@if($errors->any())<div class="login-alert"><strong>Enregistrement impossible</strong><span>{{ $errors->first() }}</span></div>@endif
<section class="admin-section"><form class="content-form" method="post" action="{{ $role->exists?route('admin.roles.update',$role):route('admin.roles.store') }}">@csrf @if($role->exists)@method('PUT')@endif<div class="form-grid"><label>Nom du role<input name="name" value="{{ old('name',$role->name) }}" required></label><label>Code interne<input name="slug" value="{{ old('slug',$role->slug) }}" pattern="[A-Za-z0-9_-]+" @readonly($role->protected) placeholder="ex: chef_agence"></label><label class="field-wide">Description<textarea name="description" rows="3">{{ old('description',$role->description) }}</textarea></label>@if($role->exists&&!$role->protected)<label class="consent-check"><input type="checkbox" name="active" value="1" @checked(old('active',$role->active))><span>Role actif et disponible pour les utilisateurs</span></label>@endif</div><div class="permission-grid">@foreach($permissions as $permission)<label class="permission-card"><input type="checkbox" name="permissions[]" value="{{ $permission->id }}" @checked(in_array($permission->id, old('permissions',$selectedPermissions), false))><span><strong>{{ $permission->name }}</strong><small>{{ $permission->description }}</small></span></label>@endforeach</div><div class="form-actions"><button class="btn primary">{{ $role->exists?'Enregistrer le role':'Creer le role' }}</button></div></form></section>
@if($role->exists&&!$role->protected)<section class="admin-section delete-zone"><div><p class="eyebrow">Suppression</p><h2>Supprimer ce role</h2><p>La suppression est possible uniquement si aucun utilisateur n'utilise ce role.</p></div><form method="post" action="{{ route('admin.roles.destroy',$role) }}" onsubmit="return confirm('Supprimer definitivement ce role ?')">@csrf @method('DELETE')<button class="btn danger">Supprimer le role</button></form></section>@endif
@endsection
