@extends('admin.layout')
@section('title','Retours clients')
@php($active='feedback')
@section('content')
<div class="admin-page-heading"><div><p class="eyebrow">Qualite client</p><h1>Retours d'experience</h1><p>Centralisez les avis, suggestions et reclamations recus.</p></div></div>
<div class="metrics admin-metrics feedback-metrics"><article class="metric"><strong>{{ $metrics['total'] }}</strong><span>Retours recus</span></article><article class="metric"><strong>{{ $metrics['average'] ?: '-' }}/5</strong><span>Note moyenne</span></article><article class="metric"><strong>{{ $metrics['open'] }}</strong><span>A traiter</span></article><article class="metric"><strong>{{ $metrics['complaints'] }}</strong><span>Reclamations ouvertes</span></article></div>
<section class="admin-section"><form class="feedback-filters" method="get"><label>Statut<select name="status"><option value="">Tous</option>@foreach(['Nouveau','En cours','Traite','Clos'] as $status)<option value="{{ $status }}" @selected(request('status')===$status)>{{ $status }}</option>@endforeach</select></label><label>Type<select name="type"><option value="">Tous</option>@foreach(['Avis','Reclamation','Suggestion'] as $type)<option value="{{ $type }}" @selected(request('type')===$type)>{{ $type }}</option>@endforeach</select></label><label>Note<select name="rating"><option value="">Toutes</option>@foreach(range(5,1) as $rating)<option value="{{ $rating }}" @selected((string)request('rating')===(string)$rating)>{{ $rating }}/5</option>@endforeach</select></label><button class="btn primary">Filtrer</button><a class="btn secondary" href="{{ route('admin.feedback.index') }}">Reinitialiser</a></form></section>
<section class="admin-section"><div class="request-table-wrap"><table class="request-table"><thead><tr><th>Reference</th><th>Client</th><th>Type</th><th>Theme</th><th>Note</th><th>Priorite</th><th>Statut</th><th>Action</th></tr></thead><tbody>@forelse($feedbackItems as $item)<tr><td><strong>{{ $item->reference }}</strong><br><small>{{ $item->created_at->format('d/m/Y H:i') }}</small></td><td>{{ $item->customer_name }}<br><small>{{ $item->email }}</small></td><td>{{ $item->type }}</td><td>{{ $item->category }}</td><td><span class="rating-value">{{ $item->rating }}/5</span></td><td><span class="priority priority-{{ Str::slug($item->priority) }}">{{ $item->priority }}</span></td><td>{{ $item->status }}</td><td><a class="btn secondary table-action" href="{{ route('admin.feedback.show',$item) }}">Voir / Traiter</a></td></tr>@empty<tr><td colspan="8">Aucun retour client ne correspond aux filtres.</td></tr>@endforelse</tbody></table></div><div class="pagination-links">{{ $feedbackItems->links() }}</div></section>
@endsection
