@extends('admin.layout')
@section('title','Retour '.$customerFeedback->reference)
@php($active='feedback')
@section('content')
<div class="admin-page-heading"><div><p class="eyebrow">{{ $customerFeedback->type }} - {{ $customerFeedback->reference }}</p><h1>{{ $customerFeedback->customer_name }}</h1><p>Recu le {{ $customerFeedback->created_at->format('d/m/Y a H:i') }}</p></div><a class="btn secondary" href="{{ route('admin.feedback.index') }}">Retour aux retours</a></div>
@if($errors->any())<div class="login-alert"><strong>Action impossible</strong><span>{{ $errors->first() }}</span></div>@endif
<div class="quote-detail-grid"><section class="admin-section"><p class="eyebrow">Client</p><h2>Coordonnees</h2><dl class="detail-list"><div><dt>Nom</dt><dd>{{ $customerFeedback->customer_name }}</dd></div><div><dt>Email</dt><dd><a href="mailto:{{ $customerFeedback->email }}">{{ $customerFeedback->email }}</a></dd></div><div><dt>Telephone</dt><dd>{{ $customerFeedback->phone ?: 'Non renseigne' }}</dd></div><div><dt>Demande liee</dt><dd>@if($customerFeedback->quoteRequest)<a href="{{ route('admin.quotes.show',$customerFeedback->quoteRequest) }}">{{ $customerFeedback->quoteRequest->reference }}</a>@else Non identifiee @endif</dd></div></dl></section>
<section class="admin-section"><p class="eyebrow">Experience</p><h2>{{ $customerFeedback->rating }}/5 - {{ $customerFeedback->category }}</h2><div class="client-message"><strong>{{ $customerFeedback->type }}</strong><p>{{ $customerFeedback->message }}</p></div></section></div>
<section class="admin-section"><p class="eyebrow">Traitement interne</p><h2>Suivi du retour</h2><form class="content-form" method="post" action="{{ route('admin.feedback.update',$customerFeedback) }}">@csrf @method('PUT')<div class="form-grid"><label>Statut<select name="status">@foreach(['Nouveau','En cours','Traite','Clos'] as $status)<option @selected(old('status',$customerFeedback->status)===$status)>{{ $status }}</option>@endforeach</select></label><label>Priorite<select name="priority">@foreach(['Basse','Normale','Haute','Critique'] as $priority)<option @selected(old('priority',$customerFeedback->priority)===$priority)>{{ $priority }}</option>@endforeach</select></label><label class="field-wide">Reponse et actions menees<textarea name="admin_response" rows="8" placeholder="Compte rendu du traitement, appel effectue, solution proposee...">{{ old('admin_response',$customerFeedback->admin_response) }}</textarea></label></div><button class="btn primary">Enregistrer le traitement</button></form>@if($customerFeedback->handler)<p class="handling-note">Derniere prise en charge par {{ $customerFeedback->handler->name }}{{ $customerFeedback->handled_at ? ' le '.$customerFeedback->handled_at->format('d/m/Y a H:i') : '' }}.</p>@endif</section>
<section class="admin-section delete-zone"><div><p class="eyebrow">Zone sensible</p><h2>Supprimer le retour client</h2><p>Cette action effacera definitivement ce retour d'experience. Elle ne peut pas etre annulee.</p></div><form method="post" action="{{ route('admin.feedback.destroy',$customerFeedback) }}" onsubmit="return confirm('Supprimer definitivement le retour {{ $customerFeedback->reference }} ?')">@csrf @method('DELETE')<button class="btn danger">Supprimer ce retour</button></form></section>
@endsection
