<?php
use App\Http\Controllers\AdminController;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\QuoteRequestController;
use App\Http\Controllers\SiteSettingController;
use App\Http\Controllers\VehicleController;
use App\Http\Controllers\CustomerFeedbackController;
use App\Http\Controllers\SmsCampaignController;
use App\Http\Controllers\UserManagementController;
use App\Http\Controllers\RoleManagementController;
use App\Http\Controllers\AnnouncementMessageController;
use Illuminate\Support\Facades\Route;
Route::get('/',[HomeController::class,'index'])->name('home');
Route::post('/devis',[QuoteRequestController::class,'store'])->name('quotes.store');
Route::post('/retours-experience',[CustomerFeedbackController::class,'store'])->name('feedback.store');
Route::get('/documents/{quoteMessage}/telecharger',[QuoteRequestController::class,'downloadAttachment'])->middleware('signed')->name('quote-attachments.download');
Route::middleware('guest')->group(function(){Route::get('/connexion',[AuthController::class,'showLogin'])->name('login');Route::post('/connexion',[AuthController::class,'login'])->name('login.store');});
Route::post('/deconnexion',[AuthController::class,'logout'])->middleware('auth')->name('logout');
Route::get('/mot-de-passe',[AuthController::class,'showChangePassword'])->middleware('auth')->name('password.change');
Route::put('/mot-de-passe',[AuthController::class,'updatePassword'])->middleware('auth')->name('password.update');
Route::prefix('administration')->name('admin.')->middleware(['auth','password.changed'])->group(function(){
 Route::get('/',[AdminController::class,'dashboard'])->middleware('permission:dashboard')->name('dashboard');
 Route::get('/demandes',[AdminController::class,'quotes'])->middleware('permission:quotes')->name('quotes.index');
 Route::get('/vehicules',[AdminController::class,'vehicles'])->middleware('permission:vehicles')->name('vehicles.index');
 Route::get('/contenus',[AdminController::class,'settings'])->middleware('permission:settings')->name('settings.edit');
 Route::get('/messages-pop-up',[AnnouncementMessageController::class,'index'])->middleware('permission:settings')->name('announcements.index');
 Route::get('/messages-pop-up/creer',[AnnouncementMessageController::class,'create'])->middleware('permission:settings')->name('announcements.create');
 Route::post('/messages-pop-up',[AnnouncementMessageController::class,'store'])->middleware('permission:settings')->name('announcements.store');
 Route::get('/messages-pop-up/{announcement}/modifier',[AnnouncementMessageController::class,'edit'])->middleware('permission:settings')->name('announcements.edit');
 Route::put('/messages-pop-up/{announcement}',[AnnouncementMessageController::class,'update'])->middleware('permission:settings')->name('announcements.update');
 Route::delete('/messages-pop-up/{announcement}',[AnnouncementMessageController::class,'destroy'])->middleware('permission:settings')->name('announcements.destroy');
 Route::get('/retours-clients',[CustomerFeedbackController::class,'index'])->middleware('permission:feedback')->name('feedback.index');
 Route::get('/retours-clients/{customerFeedback}',[CustomerFeedbackController::class,'show'])->middleware('permission:feedback')->name('feedback.show');
 Route::put('/retours-clients/{customerFeedback}',[CustomerFeedbackController::class,'update'])->middleware('permission:feedback')->name('feedback.update');
 Route::delete('/retours-clients/{customerFeedback}',[CustomerFeedbackController::class,'destroy'])->middleware('permission:feedback')->name('feedback.destroy');
 Route::get('/sms',[SmsCampaignController::class,'index'])->middleware('permission:sms')->name('sms.index');
 Route::get('/sms/campagnes/nouvelle',[SmsCampaignController::class,'create'])->middleware('permission:sms')->name('sms.create');
 Route::post('/sms/campagnes',[SmsCampaignController::class,'store'])->middleware('permission:sms')->name('sms.store');
 Route::get('/sms/campagnes/{smsCampaign}',[SmsCampaignController::class,'show'])->middleware('permission:sms')->name('sms.show');
 Route::post('/sms/campagnes/{smsCampaign}/test',[SmsCampaignController::class,'sendTest'])->middleware('permission:sms')->name('sms.test');
 Route::post('/sms/campagnes/{smsCampaign}/envoyer',[SmsCampaignController::class,'launch'])->middleware('permission:sms')->name('sms.launch');
 Route::post('/sms/campagnes/{smsCampaign}/whatsapp/{smsMessage}/confirmer',[SmsCampaignController::class,'confirmWhatsApp'])->middleware('permission:sms')->name('sms.whatsapp.confirm');
 Route::put('/contenus',[SiteSettingController::class,'update'])->middleware('permission:settings')->name('settings.update');
 Route::patch('/demandes/{quoteRequest}/statut',[QuoteRequestController::class,'updateStatus'])->middleware('permission:quotes')->name('quotes.status');
 Route::get('/demandes/{quoteRequest}',[QuoteRequestController::class,'show'])->middleware('permission:quotes')->name('quotes.show');
 Route::put('/demandes/{quoteRequest}',[QuoteRequestController::class,'manage'])->middleware('permission:quotes')->name('quotes.manage');
 Route::post('/demandes/{quoteRequest}/email',[QuoteRequestController::class,'sendEmail'])->middleware('permission:quotes')->name('quotes.email');
 Route::delete('/demandes/{quoteRequest}',[QuoteRequestController::class,'destroy'])->middleware('permission:quotes')->name('quotes.destroy');
 Route::get('/vehicules/creer',[VehicleController::class,'create'])->middleware('permission:vehicles')->name('vehicles.create');
 Route::post('/vehicules',[VehicleController::class,'store'])->middleware('permission:vehicles')->name('vehicles.store');
 Route::get('/vehicules/{vehicle}/modifier',[VehicleController::class,'edit'])->middleware('permission:vehicles')->name('vehicles.edit');
 Route::put('/vehicules/{vehicle}',[VehicleController::class,'update'])->middleware('permission:vehicles')->name('vehicles.update');
 Route::post('/vehicules/{vehicle}/images',[VehicleController::class,'uploadImage'])->middleware('permission:vehicles')->name('vehicles.images.store');
 Route::delete('/vehicules/{vehicle}/images/{image}',[VehicleController::class,'destroyImage'])->middleware('permission:vehicles')->name('vehicles.images.destroy');
 Route::get('/utilisateurs',[UserManagementController::class,'index'])->middleware('permission:users')->name('users.index');
 Route::get('/utilisateurs/creer',[UserManagementController::class,'create'])->middleware('permission:users')->name('users.create');
 Route::post('/utilisateurs',[UserManagementController::class,'store'])->middleware('permission:users')->name('users.store');
 Route::get('/utilisateurs/{user}/modifier',[UserManagementController::class,'edit'])->middleware('permission:users')->name('users.edit');
 Route::put('/utilisateurs/{user}',[UserManagementController::class,'update'])->middleware('permission:users')->name('users.update');
 Route::post('/utilisateurs/{user}/mot-de-passe',[UserManagementController::class,'resetPassword'])->middleware('permission:users')->name('users.password');
 Route::get('/roles',[RoleManagementController::class,'index'])->middleware('permission:users')->name('roles.index');
 Route::get('/roles/creer',[RoleManagementController::class,'create'])->middleware('permission:users')->name('roles.create');
 Route::post('/roles',[RoleManagementController::class,'store'])->middleware('permission:users')->name('roles.store');
 Route::get('/roles/{role}/modifier',[RoleManagementController::class,'edit'])->middleware('permission:users')->name('roles.edit');
 Route::put('/roles/{role}',[RoleManagementController::class,'update'])->middleware('permission:users')->name('roles.update');
 Route::delete('/roles/{role}',[RoleManagementController::class,'destroy'])->middleware('permission:users')->name('roles.destroy');
});
