@extends('admin.layout')
@section('title',$announcement->exists?'Modifier un message':'Creer un message')
@php($active='announcements')
@section('content')
<div class="admin-page-heading"><div><p class="eyebrow">Bande defilante</p><h1>{{ $announcement->exists?'Modifier le message':'Nouveau message' }}</h1><p>Le message actif s'affichera entre l'en-tete blanc et le visuel d'accueil.</p></div><a class="btn secondary" href="{{ route('admin.announcements.index') }}">Retour aux messages</a></div>
@if($errors->any())<div class="login-alert"><strong>Enregistrement impossible</strong><span>{{ $errors->first() }}</span></div>@endif
<section class="admin-section"><form class="content-form" method="post" action="{{ $announcement->exists?route('admin.announcements.update',$announcement):route('admin.announcements.store') }}">@csrf @if($announcement->exists)@method('PUT')@endif<div class="form-grid"><label>Titre court<input name="title" value="{{ old('title',$announcement->title) }}" maxlength="120" placeholder="Ex: Information UTB"></label><label>Style<select name="style" required>@foreach(['info'=>'Information','urgent'=>'Urgent','success'=>'Confirmation'] as $value=>$label)<option value="{{ $value }}" @selected(old('style',$announcement->style)===$value)>{{ $label }}</option>@endforeach</select></label><label class="field-wide">Message<textarea name="message" rows="4" maxlength="500" required>{{ old('message',$announcement->message) }}</textarea></label><label>Ordre d'affichage<input name="position" type="number" min="0" max="999" value="{{ old('position',$announcement->position ?? 0) }}" required></label><label>Debut de diffusion<input name="starts_at" type="datetime-local" value="{{ old('starts_at',$announcement->starts_at?->format('Y-m-d\TH:i')) }}"></label><label>Fin de diffusion<input name="ends_at" type="datetime-local" value="{{ old('ends_at',$announcement->ends_at?->format('Y-m-d\TH:i')) }}"></label><label class="consent-check"><input type="checkbox" name="active" value="1" @checked(old('active',$announcement->active))><span>Message actif et visible dans la bande defilante</span></label></div><button class="btn primary">{{ $announcement->exists?'Enregistrer le message':'Creer le message' }}</button></form></section>
@if($announcement->exists)<section class="admin-section delete-zone"><div><p class="eyebrow">Suppression</p><h2>Supprimer ce message</h2><p>Le message sera retire de la bande defilante et de l'administration.</p></div><form method="post" action="{{ route('admin.announcements.destroy',$announcement) }}" onsubmit="return confirm('Supprimer definitivement ce message ?')">@csrf @method('DELETE')<button class="btn danger">Supprimer le message</button></form></section>@endif
@endsection
