@extends('admin.layout')
@section('title','Nouvelle campagne client')
@php($active='sms')
@section('content')
<div class="admin-page-heading"><div><p class="eyebrow">Nouvelle campagne</p><h1>Composer la communication</h1><p>Choisissez un seul canal : SMS, e-mail ou WhatsApp.</p></div><a class="btn secondary" href="{{ route('admin.sms.index') }}">Retour</a></div>
@if($errors->any())<div class="login-alert"><strong>Campagne non enregistree</strong><span>{{ $errors->first() }}</span></div>@endif
<form class="content-form sms-composer" method="post" action="{{ route('admin.sms.store') }}">@csrf
<section class="admin-section"><h2>Canal d'envoi</h2><div class="sms-audience-options channel-options"><label><input type="radio" name="channel" value="email" @checked(old('channel','email')==='email')><span>Email uniquement</span></label><label><input type="radio" name="channel" value="sms" @checked(old('channel')==='sms')><span>SMS uniquement</span></label><label><input type="radio" name="channel" value="whatsapp" @checked(old('channel')==='whatsapp')><span>WhatsApp uniquement</span></label></div><p class="channel-advice" id="channelAdvice"></p></section>
<section class="admin-section"><h2>Message</h2><div class="form-grid"><label>Nom interne de la campagne<input name="name" value="{{ old('name') }}" placeholder="Remerciement clients juin" required></label><label id="smsSenderField">Expediteur SMS<input name="sender" value="{{ old('sender',config('sms.sender','UTBLOCATION')) }}" maxlength="11" pattern="[A-Za-z0-9]+"><small>11 caracteres maximum, sans espace.</small></label><label class="field-wide" id="emailSubjectField">Objet de l'email<input name="email_subject" value="{{ old('email_subject','UTB vous remercie pour votre confiance') }}" maxlength="180"></label><label class="field-wide">Corps du message<textarea id="campaignMessage" name="message" rows="9" maxlength="5000" required>{{ old('message','Bonjour {nom}, UTB vous remercie pour votre confiance. Nous restons a votre disposition pour votre prochaine location.') }}</textarea><small><span id="messageCharacters">0</span> caracteres<span id="smsSegmentInfo"></span>. Variables : {nom}, {reference}, {destination}, {date}.</small></label></div></section>
<section class="admin-section"><h2>Destinataires</h2><div class="sms-audience-options"><label><input type="radio" name="audience" value="all" @checked(old('audience','all')==='all')><span>Tous les consentants</span></label><label><input type="radio" name="audience" value="confirmed" @checked(old('audience')==='confirmed')><span>Locations confirmees</span></label><label><input type="radio" name="audience" value="selected" @checked(old('audience')==='selected')><span>Selection manuelle</span></label></div><div class="sms-contact-list" id="campaignContactList">@forelse($contacts as $contact)<label data-sms="{{ $contact->sms_consent?1:0 }}" data-email="{{ $contact->email_consent&&$contact->email?1:0 }}" data-whatsapp="{{ $contact->whatsapp_consent?1:0 }}"><input type="checkbox" name="recipients[]" value="{{ $contact->id }}" @checked(in_array($contact->id,old('recipients',[])))><span><strong>{{ $contact->name }}</strong><small>{{ $contact->phone }}{{ $contact->email?' - '.$contact->email:'' }} - {{ $contact->reference }}</small><small>{{ $contact->sms_consent?'SMS autorise':'SMS non autorise' }} | {{ $contact->email_consent?'Email autorise':'Email non autorise' }} | {{ $contact->whatsapp_consent?'WhatsApp autorise':'WhatsApp non autorise' }}</small></span></label>@empty<p>Aucun client n'a encore donne son consentement.</p>@endforelse</div></section>
<section class="admin-section"><h2>Programmation automatique</h2><label>Date et heure d'envoi facultatives<input name="scheduled_at" type="datetime-local" value="{{ old('scheduled_at') }}"><small>A la date choisie, la campagne sera envoyee automatiquement apres avoir clique sur « Programmer la campagne ». Laissez vide pour un envoi manuel.</small></label></section><button class="btn primary">Enregistrer et verifier</button></form>
@push('scripts')<script>const campaignMessage=document.querySelector('#campaignMessage'),messageCharacters=document.querySelector('#messageCharacters'),smsSegmentInfo=document.querySelector('#smsSegmentInfo'),smsSenderField=document.querySelector('#smsSenderField'),emailSubjectField=document.querySelector('#emailSubjectField'),contactList=document.querySelector('#campaignContactList'),channelAdvice=document.querySelector('#channelAdvice');function selectedChannel(){return document.querySelector('input[name="channel"]:checked').value}function refreshCampaign(){const channel=selectedChannel(),usesSms=channel==='sms',usesEmail=channel==='email',length=campaignMessage.value.length;messageCharacters.textContent=length;smsSegmentInfo.textContent=usesSms?' - environ '+(length<=160?1:Math.ceil(length/153))+' SMS':'';campaignMessage.maxLength=usesSms?480:5000;smsSenderField.hidden=!usesSms;emailSubjectField.hidden=!usesEmail;channelAdvice.textContent=channel==='email'?'Cette campagne enverra uniquement un e-mail. Aucun credit SMS ne sera utilise.':channel==='whatsapp'?'Cette campagne utilisera uniquement WhatsApp avec validation manuelle.':'Cette campagne enverra uniquement un SMS et necessite un bundle Orange actif.';document.querySelectorAll('#campaignContactList>label').forEach(label=>{label.hidden=channel==='sms'?label.dataset.sms!=='1':channel==='email'?label.dataset.email!=='1':label.dataset.whatsapp!=='1'})}function audience(){contactList.hidden=document.querySelector('input[name="audience"]:checked').value!=='selected'}campaignMessage.addEventListener('input',refreshCampaign);document.querySelectorAll('input[name="channel"]').forEach(input=>input.addEventListener('change',refreshCampaign));document.querySelectorAll('input[name="audience"]').forEach(input=>input.addEventListener('change',audience));refreshCampaign();audience();</script>@endpush
@endsection
