@extends('admin.layout')
@section('title','Campagnes clients')
@php($active='sms')
@section('content')
<div class="admin-page-heading"><div><p class="eyebrow">Fidelisation client</p><h1>Campagnes SMS, Email et WhatsApp</h1><p>Choisissez le canal adapte ou combinez-les pour joindre davantage de clients.</p></div><a class="btn primary" href="{{ route('admin.sms.create') }}">Nouvelle campagne</a></div>
<div class="sms-gateway-state {{ $gateway->driver()==='log'?'is-test':'is-live' }}"><strong>Trois canaux disponibles</strong><span>WhatsApp fonctionne manuellement sans API payante. Email : {{ config('mail.default')==='log'?'mode test':'SMTP actif' }}. SMS : {{ $gateway->driver() }}.</span></div>
<div class="metrics admin-metrics feedback-metrics"><article class="metric"><strong>{{ $metrics['campaigns'] }}</strong><span>Campagnes</span></article><article class="metric"><strong>{{ $metrics['sent'] }}</strong><span>SMS traites</span></article><article class="metric"><strong>{{ $metrics['email_sent'] }}</strong><span>Emails traites</span></article><article class="metric"><strong>{{ $metrics['whatsapp_sent'] }}</strong><span>WhatsApp confirmes</span></article></div>
<section class="admin-section"><div class="request-table-wrap"><table class="request-table"><thead><tr><th>Campagne</th><th>Canal</th><th>Audience</th><th>Destinataires</th><th>Resultat</th><th>Statut</th><th>Action</th></tr></thead><tbody>@forelse($campaigns as $campaign)<tr><td><strong>{{ $campaign->name }}</strong><br><small>{{ $campaign->created_at->format('d/m/Y H:i') }}</small></td><td>{{ ['sms'=>'SMS','email'=>'Email','both'=>'SMS + Email','whatsapp'=>'WhatsApp','all'=>'Tous les canaux'][$campaign->channel]??'SMS' }}</td><td>{{ ['all'=>'Tous','confirmed'=>'Locations confirmees','selected'=>'Selection manuelle'][$campaign->audience]??$campaign->audience }}</td><td>{{ $campaign->recipient_count }}</td><td>SMS {{ $campaign->sent_count }}/{{ $campaign->failed_count }} - Email {{ $campaign->email_sent_count }}/{{ $campaign->email_failed_count }} - WhatsApp {{ $campaign->whatsapp_sent_count }}</td><td><span class="sms-status">{{ $campaign->status }}</span></td><td><a class="btn secondary table-action" href="{{ route('admin.sms.show',$campaign) }}">Ouvrir</a></td></tr>@empty<tr><td colspan="7">Aucune campagne client.</td></tr>@endforelse</tbody></table></div>{{ $campaigns->links() }}</section>
@endsection
