@extends('admin.layout')
@section('title',$campaign->name)
@php($active='sms')
@section('content')
<div class="admin-page-heading"><div><p class="eyebrow">Campagne {{ ['sms'=>'SMS','email'=>'Email','both'=>'SMS + Email','whatsapp'=>'WhatsApp','all'=>'Tous les canaux'][$campaign->channel]??$campaign->channel }}</p><h1>{{ $campaign->name }}</h1><p>Creee par {{ $campaign->creator?->name??'UTB' }} le {{ $campaign->created_at->format('d/m/Y a H:i') }}.</p></div><a class="btn secondary" href="{{ route('admin.sms.index') }}">Retour aux campagnes</a></div>
@if(session('sms_warning'))<p class="mail-warning"><strong>{{ session('sms_warning') }}</strong></p>@endif @if($errors->any())<div class="login-alert"><strong>Action impossible</strong><span>{{ $errors->first() }}</span></div>@endif
<div class="sms-summary-grid"><section class="admin-section"><p class="eyebrow">Apercu</p>@if(in_array($campaign->channel,['sms','both','all']))<div class="phone-preview"><span class="phone-sender">{{ $campaign->sender }}</span><p>{{ $campaign->messages->where('is_test',false)->first()?->message??$campaign->message }}</p></div>@endif @if(in_array($campaign->channel,['email','both','all']))<div class="email-preview"><strong>{{ $campaign->email_subject }}</strong><p>{{ $campaign->messages->where('is_test',false)->first()?->message??$campaign->message }}</p><small>UTB Location Autocars</small></div>@endif @if(in_array($campaign->channel,['whatsapp','all']))<div class="whatsapp-preview"><strong>WhatsApp</strong><p>{{ $campaign->messages->where('is_test',false)->first()?->message??$campaign->message }}</p><small>Ouverture dans WhatsApp Web pour validation manuelle.</small></div>@endif<dl class="detail-list"><div><dt>Statut</dt><dd>{{ $campaign->status }}</dd></div><div><dt>Canal</dt><dd>{{ ['sms'=>'SMS','email'=>'Email','both'=>'SMS + Email','whatsapp'=>'WhatsApp','all'=>'Tous les canaux'][$campaign->channel] }}</dd></div><div><dt>Audience</dt><dd>{{ $campaign->recipient_count }} destinataire(s)</dd></div></dl></section>
<section class="admin-section"><p class="eyebrow">Controle avant envoi</p><h2>Preparer un test</h2><form method="post" action="{{ route('admin.sms.test',$campaign) }}" class="sms-test-form sms-test-multichannel">@csrf @if(in_array($campaign->channel,['sms','both','whatsapp','all']))<label>Numero de test<input name="phone" placeholder="0700000000" required></label>@endif @if(in_array($campaign->channel,['email','both','all']))<label>Email de test<input name="email" type="email" placeholder="nom@utb-ci.net" required></label>@endif<button class="btn secondary">Traiter le test</button></form><hr><h2>Lancer la campagne</h2>@if($campaign->status==='Brouillon')<form method="post" action="{{ route('admin.sms.launch',$campaign) }}" onsubmit="return confirm('Confirmer le traitement de {{ $campaign->recipient_count }} contact(s) ?')">@csrf<button class="btn primary">{{ $campaign->scheduled_at?->isFuture()?'Programmer la campagne':'Preparer les envois' }}</button></form>@elseif($campaign->status==='Programmee')<p class="success-message">Envoi programme.</p>@else<p>Consultez et finalisez les actions dans le journal ci-dessous.</p>@endif</section></div>
<section class="admin-section"><div class="section-head"><div><p class="eyebrow">Journal technique</p><h2>Destinataires et statuts</h2></div><div>SMS : <strong>{{ $campaign->sent_count }}</strong> / Email : <strong>{{ $campaign->email_sent_count }}</strong> / WhatsApp : <strong>{{ $campaign->whatsapp_sent_count }}</strong></div></div><div class="request-table-wrap"><table class="request-table"><thead><tr><th>Client</th><th>Coordonnees</th><th>Type</th><th>SMS</th><th>Email</th><th>WhatsApp</th><th>Action WhatsApp</th><th>Erreurs</th></tr></thead><tbody>@foreach($campaign->messages as $message)<tr><td>{{ $message->recipient_name }}</td><td>{{ $message->phone?:'-' }}<br><small>{{ $message->email?:'-' }}</small></td><td>{{ $message->is_test?'Test':'Campagne' }}</td><td>{{ $message->status }}</td><td>{{ $message->email_status }}</td><td>{{ $message->whatsapp_status }}</td><td>@if($message->whatsapp_status==='A envoyer'&&$message->whatsappUrl())<div class="whatsapp-actions"><a class="btn whatsapp-button table-action" href="{{ $message->whatsappUrl() }}" target="_blank" rel="noopener">Ouvrir WhatsApp</a><form method="post" action="{{ route('admin.sms.whatsapp.confirm',[$campaign,$message]) }}">@csrf<button class="btn secondary table-action">Marquer envoye</button></form></div>@else - @endif</td><td><small>{{ $message->error_message?:$message->email_error?:'-' }}</small></td></tr>@endforeach</tbody></table></div></section>
@endsection
