@extends('admin.layout')
@section('title',$managedUser->exists?'Modifier un utilisateur':'Creer un utilisateur')
@php($active='users')
@section('content')
<div class="admin-page-heading"><div><p class="eyebrow">Gestion des acces</p><h1>{{ $managedUser->exists?'Modifier le compte':'Nouvel utilisateur' }}</h1><p>{{ $managedUser->exists?'Ajustez le role, les coordonnees ou le statut du compte.':'Un mot de passe temporaire sera genere automatiquement.' }}</p></div><a class="btn secondary" href="{{ route('admin.users.index') }}">Retour aux utilisateurs</a></div>
@if($errors->any())<div class="login-alert"><strong>Enregistrement impossible</strong><span>{{ $errors->first() }}</span></div>@endif
@if($temporaryPassword)<div class="temporary-password"><div><p class="eyebrow">A transmettre de maniere securisee</p><strong>{{ $temporaryPassword }}</strong><p>Ce mot de passe ne sera plus affiche. L'utilisateur devra le remplacer lors de sa premiere connexion.</p></div><button type="button" class="btn secondary" data-copy-password="{{ $temporaryPassword }}">Copier</button></div>@endif
<section class="admin-section"><form class="content-form" method="post" action="{{ $managedUser->exists?route('admin.users.update',$managedUser):route('admin.users.store') }}">@csrf @if($managedUser->exists)@method('PUT')@endif<div class="form-grid"><label>Nom complet<input name="name" value="{{ old('name',$managedUser->name) }}" required></label><label>Identifiant de connexion<input name="username" value="{{ old('username',$managedUser->username) }}" pattern="[A-Za-z0-9_-]+" required></label><label>Email professionnel<input name="email" type="email" value="{{ old('email',$managedUser->email) }}" required></label><label>Role<select name="role" required>@foreach($roles as $role)<option value="{{ $role->slug }}" @selected(old('role',$managedUser->role)===$role->slug)>{{ $role->name }}{{ $role->active?'':' - suspendu' }}</option>@endforeach</select></label>@if($managedUser->exists)<label class="consent-check"><input type="checkbox" name="active" value="1" @checked(old('active',$managedUser->active))><span>Compte actif et autorise a se connecter</span></label>@endif</div><button class="btn primary">{{ $managedUser->exists?'Enregistrer les modifications':'Creer le compte' }}</button></form></section>
@if($managedUser->exists)<section class="admin-section user-security-zone"><div><p class="eyebrow">Securite</p><h2>Reinitialiser le mot de passe</h2><p>Les sessions existantes resteront valides jusqu'a leur expiration. Le nouveau mot de passe devra etre remplace a la prochaine connexion.</p></div><form method="post" action="{{ route('admin.users.password',$managedUser) }}" onsubmit="return confirm('Generer un nouveau mot de passe temporaire ?')">@csrf<button class="btn secondary">Generer un mot de passe temporaire</button></form></section>@endif
@push('scripts')<script>document.querySelector('[data-copy-password]')?.addEventListener('click',event=>{navigator.clipboard.writeText(event.currentTarget.dataset.copyPassword);event.currentTarget.textContent='Copie'});</script>@endpush
@endsection
