@extends('admin.layout')
@section('title','Demande '.$quoteRequest->reference)
@php($active='quotes')
@section('content')
<div class="admin-page-heading"><div><p class="eyebrow">Demande {{ $quoteRequest->reference }}</p><h1>{{ $quoteRequest->organization ?: $quoteRequest->name }}</h1><p>Recue le {{ $quoteRequest->created_at->format('d/m/Y a H:i') }}</p></div><a class="btn secondary" href="{{ route('admin.quotes.index') }}">Retour aux demandes</a></div>
@if(session('mail_warning'))<p class="mail-warning"><strong>{{ session('mail_warning') }}</strong></p>@endif
@if($errors->any())<div class="login-alert"><strong>Action impossible</strong><span>{{ $errors->first() }}</span></div>@endif
<div class="quote-detail-grid"><section class="admin-section"><p class="eyebrow">Informations client</p><h2>Contact</h2><dl class="detail-list"><div><dt>Nom</dt><dd>{{ $quoteRequest->name }}</dd></div><div><dt>Organisation</dt><dd>{{ $quoteRequest->organization ?: 'Non renseignee' }}</dd></div><div><dt>Telephone</dt><dd><a href="tel:{{ $quoteRequest->phone }}">{{ $quoteRequest->phone }}</a></dd></div><div><dt>Email</dt><dd>@if($quoteRequest->email)<a href="mailto:{{ $quoteRequest->email }}">{{ $quoteRequest->email }}</a>@else Non renseigne @endif</dd></div></dl></section>
<section class="admin-section"><p class="eyebrow">Prestation</p><h2>Trajet et besoin</h2><dl class="detail-list"><div><dt>Trajet</dt><dd>{{ $quoteRequest->origin }} - {{ $quoteRequest->destination }}</dd></div><div><dt>Dates</dt><dd>{{ $quoteRequest->departure_date->format('d/m/Y') }} @if($quoteRequest->return_date) au {{ $quoteRequest->return_date->format('d/m/Y') }} @endif</dd></div><div><dt>Passagers</dt><dd>{{ $quoteRequest->passengers }}</dd></div><div><dt>Prestation</dt><dd>{{ $quoteRequest->service_type }}</dd></div><div><dt>Vehicule</dt><dd>{{ $quoteRequest->vehicle?->name ?? 'Sans preference' }}</dd></div><div><dt>Chauffeur</dt><dd>{{ $quoteRequest->driver_required ? 'Oui' : 'Non' }}</dd></div></dl>@if($quoteRequest->message)<div class="client-message"><strong>Message du client</strong><p>{{ $quoteRequest->message }}</p></div>@endif</section></div>
<section class="admin-section"><p class="eyebrow">Gestion interne</p><h2>Suivi commercial</h2><form method="post" action="{{ route('admin.quotes.manage',$quoteRequest) }}" class="content-form">@csrf @method('PUT')<div class="form-grid"><label>Statut<select name="status">@foreach(['Nouvelle demande','En cours','Devis envoye','Confirmee','Annulee'] as $status)<option @selected($quoteRequest->status===$status)>{{ $status }}</option>@endforeach</select></label><label class="consent-check"><input type="checkbox" name="sms_consent" value="1" @checked($quoteRequest->sms_consent)><span>Consentement SMS confirme par le client</span></label><label class="consent-check"><input type="checkbox" name="email_consent" value="1" @checked($quoteRequest->email_consent) @disabled(!$quoteRequest->email)><span>Consentement email confirme{{ $quoteRequest->email?'':' - aucune adresse email' }}</span></label><label class="consent-check"><input type="checkbox" name="whatsapp_consent" value="1" @checked($quoteRequest->whatsapp_consent)><span>Consentement WhatsApp confirme par le client</span></label><label class="field-wide">Notes internes<textarea name="internal_notes" rows="5" placeholder="Informations visibles uniquement par l'equipe UTB">{{ old('internal_notes',$quoteRequest->internal_notes) }}</textarea></label></div><button class="btn primary">Enregistrer le suivi</button></form></section>
<section class="admin-section"><p class="eyebrow">Communication client</p><h2>Envoyer un email</h2>@if(config('mail.default')==='log')<p class="mail-warning"><strong>Mode test actif.</strong> Le message sera enregistre dans les logs Laravel. Configurez un serveur SMTP pour une livraison externe.</p>@endif @if($quoteRequest->email)<form method="post" action="{{ route('admin.quotes.email',$quoteRequest) }}" class="content-form" enctype="multipart/form-data">@csrf<div class="form-grid"><label class="field-wide">Destinataire<input value="{{ $quoteRequest->email }}" disabled></label><label class="field-wide">Objet<input name="subject" value="{{ old('subject','Votre demande de location UTB - '.$quoteRequest->reference) }}" required></label><label class="field-wide">Message<textarea name="body" rows="9" required>{{ old('body',"Nous avons bien etudie votre demande de location reference {$quoteRequest->reference}.\n\nLe service location UTB reste disponible pour finaliser votre devis et confirmer la disponibilite du vehicule.") }}</textarea></label><label class="field-wide">Document facultatif<input name="attachment" type="file" accept=".pdf,.doc,.docx,.xls,.xlsx,.ppt,.pptx,.jpg,.jpeg,.png,.webp,.zip,.rar,.txt,.csv"><small>300 Mo maximum. Jusqu'a 20 Mo : piece jointe classique. Au-dela : lien prive valable 30 jours.</small></label></div><button class="btn primary">Envoyer l'email</button></form>@else<p>Le client n'a pas fourni d'adresse email.</p>@endif</section>
<section class="admin-section"><p class="eyebrow">Historique</p><h2>Emails envoyes</h2><div class="message-history">@forelse($quoteRequest->messages as $message)<article><div><strong>{{ $message->subject }}</strong><span>{{ $message->sent_at?->format('d/m/Y H:i') ?? 'Mode test - non livre' }} par {{ $message->user?->name ?? 'UTB' }}</span></div><p>{{ $message->body }}</p>@if($message->attachment_path)<p><a class="btn secondary table-action" href="{{ $message->attachmentUrl() }}">Telecharger {{ $message->attachment_name }} ({{ number_format($message->attachment_size/1048576,1,',',' ') }} Mo)</a></p>@endif</article>@empty<p>Aucun email envoye pour cette demande.</p>@endforelse</div></section>
<section class="admin-section delete-zone"><div><p class="eyebrow">Zone sensible</p><h2>Supprimer la demande</h2><p>Cette action effacera definitivement la demande et son historique d'e-mails. Elle ne peut pas etre annulee.</p></div><form method="post" action="{{ route('admin.quotes.destroy',$quoteRequest) }}" onsubmit="return confirm('Supprimer definitivement la demande {{ $quoteRequest->reference }} ?')">@csrf @method('DELETE')<button class="btn danger">Supprimer cette demande</button></form></section>
@endsection
