<?php
namespace App\Http\Controllers;
use App\Models\QuoteRequest;
use App\Models\SmsCampaign;
use App\Models\SmsMessage;
use App\Services\SmsCampaignSender;
use App\Services\SmsGateway;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Validation\Rule;
use Illuminate\View\View;
class SmsCampaignController extends Controller {
 public function index(SmsGateway $gateway): View{return view('admin.sms.index',['campaigns'=>SmsCampaign::latest()->paginate(30),'metrics'=>['campaigns'=>SmsCampaign::count(),'sent'=>SmsMessage::whereIn('status',['Envoye','Accepte par Orange','Journalise','Livre'])->where('is_test',false)->count(),'email_sent'=>SmsMessage::whereIn('email_status',['Envoye','Journalise'])->where('is_test',false)->count(),'whatsapp_sent'=>SmsMessage::where('whatsapp_status','Envoye manuellement')->where('is_test',false)->count(),'contacts'=>QuoteRequest::where(fn($q)=>$q->where('sms_consent',true)->orWhere('email_consent',true)->orWhere('whatsapp_consent',true))->count()],'gateway'=>$gateway]);}
 public function create(SmsGateway $gateway): View{return view('admin.sms.create',['contacts'=>QuoteRequest::where(fn($q)=>$q->where('sms_consent',true)->orWhere('email_consent',true)->orWhere('whatsapp_consent',true))->latest()->get(),'gateway'=>$gateway]);}
 public function store(Request $request,SmsGateway $gateway): RedirectResponse {
  $data=$request->validate(['name'=>'required|string|max:150','channel'=>'nullable|in:sms,email,whatsapp','sender'=>['nullable','string','max:11','regex:/^[A-Za-z0-9]+$/'],'email_subject'=>'nullable|string|max:180','message'=>'required|string|max:5000','audience'=>'required|in:all,confirmed,selected','recipients'=>'nullable|array|max:500','recipients.*'=>'integer|exists:quote_requests,id','scheduled_at'=>'nullable|date']);$data['channel']=$data['channel']??'sms';$usesSms=$this->usesSms($data['channel']);$usesEmail=$this->usesEmail($data['channel']);$usesWhats=$this->usesWhatsApp($data['channel']);
  if($usesSms&&empty($data['sender']))return back()->withInput()->withErrors(['sender'=>'L expediteur est obligatoire pour le canal SMS.']);if($usesSms&&mb_strlen($data['message'])>480)return back()->withInput()->withErrors(['message'=>'Un message contenant un SMS est limite a 480 caracteres.']);if($usesEmail&&empty($data['email_subject']))return back()->withInput()->withErrors(['email_subject'=>'L objet de l email est obligatoire.']);
  $query=QuoteRequest::query()->where(function($q)use($usesSms,$usesEmail,$usesWhats){if($usesSms)$q->orWhere('sms_consent',true);if($usesEmail)$q->orWhere(fn($e)=>$e->where('email_consent',true)->whereNotNull('email'));if($usesWhats)$q->orWhere('whatsapp_consent',true);});if($data['audience']==='confirmed')$query->where('status','Confirmee');if($data['audience']==='selected')$query->whereIn('id',$data['recipients']??[]);$unique=[];
  foreach($query->latest()->get() as $quote){$smsAllowed=$usesSms&&$quote->sms_consent;$waAllowed=$usesWhats&&$quote->whatsapp_consent;$phone=($smsAllowed||$waAllowed)?$gateway->normalizePhone($quote->phone):null;$email=$usesEmail&&$quote->email_consent&&$quote->email?strtolower($quote->email):null;if(!$phone&&!$email)continue;$key=$email?:$phone;if(!isset($unique[$key]))$unique[$key]=[$quote,$phone,$email,$smsAllowed,$waAllowed];}
  if(!$unique)return back()->withInput()->withErrors(['recipients'=>'Aucun contact valide et consentant ne correspond au canal choisi.']);$campaign=DB::transaction(function()use($data,$unique,$request){$campaign=SmsCampaign::create(['name'=>$data['name'],'channel'=>$data['channel'],'sender'=>strtoupper(($data['sender']??null)?:config('sms.sender')),'message'=>$data['message'],'email_subject'=>$data['email_subject']??null,'audience'=>$data['audience'],'scheduled_at'=>$data['scheduled_at']??null,'recipient_count'=>count($unique),'created_by'=>$request->user()->id]);foreach($unique as [$quote,$phone,$email,$smsAllowed,$waAllowed])$campaign->messages()->create(['quote_request_id'=>$quote->id,'recipient_name'=>$quote->name,'phone'=>$phone?:'','email'=>$email,'message'=>$this->personalize($data['message'],$quote),'status'=>$smsAllowed?'En attente':'Non requis','email_status'=>$email?'En attente':'Non requis','whatsapp_status'=>$waAllowed?'A envoyer':'Non requis']);return $campaign;});return redirect()->route('admin.sms.show',$campaign)->with('admin_success','Campagne enregistree. Verifiez les canaux avant l envoi.');
 }
 public function show(SmsCampaign $smsCampaign,SmsGateway $gateway): View{$smsCampaign->load(['creator','messages'=>fn($query)=>$query->orderBy('is_test')->latest()]);return view('admin.sms.show',['campaign'=>$smsCampaign,'gateway'=>$gateway]);}
 public function sendTest(Request $request,SmsCampaign $smsCampaign,SmsGateway $gateway,SmsCampaignSender $sender): RedirectResponse {$usesSms=$this->usesSms($smsCampaign->channel);$usesEmail=$this->usesEmail($smsCampaign->channel);$usesWhats=$this->usesWhatsApp($smsCampaign->channel);$data=$request->validate(['phone'=>[Rule::requiredIf($usesSms||$usesWhats),'nullable','string','max:30'],'email'=>[Rule::requiredIf($usesEmail),'nullable','email','max:150']]);$phone=($usesSms||$usesWhats)?$gateway->normalizePhone($data['phone']??''):null;if(($usesSms||$usesWhats)&&!$phone)return back()->withErrors(['phone'=>'Numero de test invalide.']);$record=$smsCampaign->messages()->create(['recipient_name'=>'Test UTB','phone'=>$phone?:'','email'=>$usesEmail?($data['email']??null):null,'message'=>$this->personalize($smsCampaign->message,null),'is_test'=>true,'status'=>$usesSms?'En attente':'Non requis','email_status'=>$usesEmail?'En attente':'Non requis','whatsapp_status'=>$usesWhats?'A envoyer':'Non requis']);$record=$sender->process($smsCampaign,$record);$errors=array_filter([$record->status==='Echec'?'SMS : '.$record->error_message:null,$record->email_status==='Echec'?'Email : '.$record->email_error:null]);if($errors)return back()->withErrors(['test'=>implode(' | ',$errors)]);return back()->with('sms_warning','Test prepare. SMS : '.$record->status.' - Email : '.$record->email_status.' - WhatsApp : '.$record->whatsapp_status.'.');}
 public function launch(SmsCampaign $smsCampaign,SmsCampaignSender $sender): RedirectResponse {if($smsCampaign->scheduled_at?->isFuture()){$smsCampaign->update(['status'=>'Programmee']);return back()->with('admin_success','Campagne programmee pour le '.$smsCampaign->scheduled_at->format('d/m/Y a H:i').'.');}$sender->send($smsCampaign);return back()->with('admin_success','Traitement termine. Consultez les statuts de chaque canal.');}
 public function confirmWhatsApp(SmsCampaign $smsCampaign,SmsMessage $smsMessage,SmsCampaignSender $sender): RedirectResponse {abort_unless($smsMessage->sms_campaign_id===$smsCampaign->id&&$this->usesWhatsApp($smsCampaign->channel),404);$smsMessage->update(['whatsapp_status'=>'Envoye manuellement','whatsapp_sent_at'=>now()]);$sender->refreshStatus($smsCampaign);return back()->with('admin_success','Envoi WhatsApp confirme dans l historique.');}
 private function usesSms(string $channel): bool{return in_array($channel,['sms','both','all'],true);}private function usesEmail(string $channel): bool{return in_array($channel,['email','both','all'],true);}private function usesWhatsApp(string $channel): bool{return in_array($channel,['whatsapp','all'],true);}
 private function personalize(string $message,?QuoteRequest $quote): string{return strtr($message,['{nom}'=>$quote?->name??'Client UTB','{reference}'=>$quote?->reference??'TEST-UTB','{destination}'=>$quote?->destination??'votre destination','{date}'=>$quote?->departure_date?->format('d/m/Y')??now()->format('d/m/Y')]);}
}
